[package]
name = "kaze-sim-tests"
version = "0.1.0"
authors = ["ferris <yupferris@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
kaze = { path = "../kaze" }

[dependencies]
